CREATE DATABASE APMS;

CREATE USER 'employee'@'localhost' IDENTIFIED BY 'password';
CREATE USER 'employee'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON APMS.* TO 'employee'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON APMS.* TO 'employee'@'%' WITH GRANT OPTION;

USE APMS;

-- CREATE TABLE EMPLOYEE
CREATE TABLE APMS.EMPLOYEE
(
	EMPLOYEE_ID         INTEGER     NOT NULL AUTO_INCREMENT,
    EMPLOYEE_FIRSTNAME  VARCHAR(80) NOT NULL,
    EMPLOYEE_LASTNAME   VARCHAR(80) NOT NULL,
	EMPLOYEE_USERNAME   VARCHAR(15) NOT NULL UNIQUE,
    EMPLOYEE_PASSWORD   VARCHAR(50) NOT NULL,
	PRIMARY KEY(EMPLOYEE_ID)
);

-- Load data into EMPLOYEE table
INSERT INTO APMS.EMPLOYEE VALUES('1', 'Admin', 'Admin', 'admin', 'password');
INSERT INTO APMS.EMPLOYEE VALUES('2', 'Karanveer',  'Khanna', 'karan', 'password');
INSERT INTO APMS.EMPLOYEE VALUES('3', 'Ryan', 'Liang', 'ryan', 'password');
INSERT INTO APMS.EMPLOYEE VALUES('4', 'Test', 't', 'test', 'password');